server:
  port: 8080

spring:
  application:
    name: flowmind-app-service
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/FlowMind?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_0900_ai_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

flowmind:
  minio:
    endpoint: http://localhost:9000
    bucket: flowmind-demo
  llm:
    provider: deepseek
    base-url: https://api.deepseek.com
    chat-path: /chat/completions
    model: deepseek-chat
    api-key: sk-6e80807ed21c44cc90fc124445e38865
    temperature: 0.7
    max-tokens: 4096
  tools:
    web:
      enabled: true
      search-url: https://duckduckgo.com/html/?q=
    lark-cli:
      enabled: true
      command: lark-cli
      timeout-seconds: 30
  feishu:
    mode: mock
    knowledge-base:
      name: 保研知识库
      folder-token: KELsfW0jvlHcVqdiuTncQ66Lnnc
      url: https://ycn1ft0idflw.feishu.cn/drive/folder/KELsfW0jvlHcVqdiuTncQ66Lnnc
  embedding:
    provider: dashscope
    api-key: sk-ws-H.REYXIEE.s9Gp.MEYCIQC91wjQTTwakFFenO7y9TXn-hv3T-k-AjsKG9vkLZ4FKQIhAMmICW8qdzRgvpbOJOcZXypXab0LpS5k_ZFHAi-iOVuG
    model: text-embedding-v4
  weaviate:
    enabled: true
    base-url: http://localhost:18080
    scheme: http
  vector-demo:
    enabled: true
    fallback-enabled: true
    max-top-k: 20
    max-distance: 0.65
    agent-enabled: true
    agent-top-k: 5
    always-search: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
